In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
from mpl_toolkits.mplot3d import Axes3D

In [2]:
iris = datasets.load_iris()

X = iris.data[:, :2]             # Get the first 2 columns.
Y = iris.target

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3, random_state = 0)
#Split the set into training and testing

clf = svm.SVC(C=0.8, kernel='rbf', gamma=20, decision_function_shape='ovr')
'''
one-versus-one, that is1-v-1 SVMs, OVO SVMs, pairwise
For each two catalogy, it will produce a SVM，thus in k samples we have to
design k(k-1)/2 number of SVM.
A=B=C=D=0; 
(A, B)-classifier if A win,then A=A+1;otherwise,B=B+1; 
(A,C)-classifer if A win,then A=A+1;otherwise, C=C+1; 
(C,D)-classifer if A win,then C=C+1;otherwise,D=D+1; 
The decision is the Max(A,B,C,D) 
one-versus-rest 
'''
clf.fit(x_train, y_train.ravel())
#clf = svm.SVC(C=0.1, kernel='linear', decision_function_shape='ovr')
# rsdial basis function kernel k(xi,yi) = exp(-r||xi - yi||^2) r>0 r = 1/2sigma^2
# k(xi,xj) = (xi,xj)^d


SVC(C=0.8, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=20, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [3]:
print('Training set precision:',clf.score(x_train, y_train))# accuracy
y_hat = clf.predict(x_train)
print('Test set precision:',clf.score(x_test, y_test))
y_hat = clf.predict(x_test)

print('decision_function:\n', clf.decision_function(x_train))
#Every column is the distance to every catalogy
print('\npredict:\n', clf.predict(x_train)) # Which target/catagory

x1_min, x1_max = X[:, 0].min(), X[:, 0].max() # range of row 0
x2_min, x2_max = X[:, 1].min(), X[:, 1].max() # range of row 1
x1, x2 = np.mgrid[x1_min:x1_max:200j, x2_min:x2_max:200j] #training points
grid_test = np.stack((x1.flat, x2.flat), axis=1) # testing points
# print 'grid_test = \n', grid_testgrid_hat = clf.predict(grid_test)      
# predict the classifier grid_hat = grid_hat.reshape(x1.shape) 
'''mgrid() function F(x,y) = x+y
Step1 x span to the right
[1 1 1]
[2 2 2]
[3 3 3]
step 2 y span to the down side
[4 5 6]
[4 5 6]
[4 5 6]
step 3 
[(1,4)(1,5)(1,6)]
[(2,4)(2,5)(2,6)]
[(3,4)(3,5)(3,6)]
step 4 plug in (xi,yi) 
'''
'''
We wold like to find a transformation of the data T:R^n to R^n
'''

Training set precision: 0.8761904761904762
Test set precision: 0.6666666666666666
decision_function:
 [[-0.26496148  2.31320556  0.95175593]
 [-0.46460103  1.0069957   2.45760533]
 [-0.34406807  0.88669571  2.45737235]
 [-0.33663974  0.94499968  2.39164007]
 [-0.26092765  0.80359001  2.45733763]
 [-0.41227069  2.45224614  0.96002455]
 [-0.24916617  0.79185614  2.45731002]
 [-0.46658731  1.04419605  2.42239126]
 [-0.35231227  2.47502681  0.87728546]
 [-0.39306788  0.93582612  2.45724176]
 [-0.40608284  0.93841843  2.46766442]
 [-0.43745964  1.1734242   2.26403544]
 [-0.45742019  1.18117017  2.27625003]
 [-0.45426871  1.04748839  2.40678032]
 [-0.46460103  1.0069957   2.45760533]
 [-0.35218559  2.30517692  1.04700868]
 [ 2.47234131 -0.32113958  0.84879827]
 [-0.45733812  2.33815922  1.1191789 ]
 [-0.3821427   2.45738211  0.92476059]
 [-0.32999198  2.47836427  0.85162771]
 [-0.35008225  2.4574273   0.89265494]
 [-0.43536684  1.09667167  2.33869516]
 [-0.33054945  0.87308262  2.45746683]
 

'\nWe wold like to find a transformation of the data T:R^n to R^n\n'